spring:
  profiles:
    active: pro

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: counSql
  reasonable: true

# 以下配置没有用到
application:
  jwt-secret: com.infoearth.develop.jwt #JWT密钥,请保存好
  jwt-exp: 168                          #认证过期时间，默认7天
  verify-token: false                   #是否验证token
  application-dir: ${app.home}
  srs-Dir:
  user:
